### PR TITLE
Add Bitfocus Companion tally server

### PR DESCRIPTION
**Pull request by peternewman**
I'm assuming you're happy to have this sort of thing listed? Hopefully it will help uptake in the clock too.

I don't know if you want it listed on the front page or under the tally protocol docs (or a simpler pointer from one to the other).

### CODE REVIEW

**Comment by simonhyde** [comment]
call that an authentication implementation? ;-)

**Comment by peternewman** [comment]
Fair point, I've opened https://github.com/bitfocus/companion-module-simonhyde-piclock/issues/1 to track it. I assume you're mostly worried about unauthorised data exfiltration (given we are the server), aside from a client could send in fake GPI data I guess.

**Comment by SimonHyde-BBC** [comment]
I guess I've never thought before exactly what the authentication is protecting against. It also prevents unauthrised clients sitting with connections on your serve hogging resources (as my implementation will kick off a client that's failed to authenticate within a reasonably short period of time)?

I'd also like to tweak the protocol to get servers authenticating themselves to clients too https://github.com/simonhyde/PiClock/issues/15

**Comment by simonhyde** [comment]
I guess I've never thought before exactly what the authentication is protecting against. It also prevents unauthrised clients sitting with connections on your serve hogging resources (as my implementation will kick off a client that's failed to authenticate within a reasonably short period of time)?

I'd also like to tweak the protocol to get servers authenticating themselves to clients too https://github.com/simonhyde/PiClock/issues/17

**Pull request merged**
